# Note: Not every parameter is relevant for every experiment type. 
# Note: Not all parameter configurations are tested yet. 

experiment:
  experiment_type: gnm_sweep  # Options: esn, gnm_sweep, gnm_comprehensive, full_pipeline, gnm_esn_grid
  type: gnm_sweep
  name: 49_shafiei # _with_eval_of_emp_conns # connectomes_of_size_50
  animal: 0 # Change this somehow: Make it not necessary for the shafiei dataset, and make it indented
  compare_to_connectome_of_distance_matrix: true
  average_connectomes: true 
  elaborate_analysis: true  # check if this is ingored?? (should not be, hopefully)
  compare_to_all_individual_empirical_connectomes: false # TODO: Add individual matrices from 70_conns dataset first!! # true # false # ADD EMPIRICAL CONNECTOME LOADING FIRST! true # true # include this - this is currently not parsed by yaml...
  search: 
    method: random # Edit: There are currently no alternatives included. Previously, options were: grid, random, bayesian
    n_samples: 30 #  # For random search
  wandb:
    enabled: false
    project: GNM_project # GNM_Pipeline
  compare_rules: true  # For gnm_comprehensive
  fit_weights: true    # For gnm_comprehensive

data:
  dataset_name: shafiei_human_consensus_dataset
  connectome_resolution: 68 # 50 # 68 # 1000 # 114, 68
  density: 10

gnm:
  eta_range: [-11.0, 0.0] # [-7.0, 0.0] # [-3.0, 0.0] # Attention: Too big values may lead to numerical instabilities! e.g.: [-5.0, 0.0] 
  gamma_range: [-1, 1.0] # Attention: Too big values may lead to numerical instabilities! e.g.: [0.0, 1.0]
  lambda: 0.0
  # n_eta: 100 # 10  # Number of eta grid points. Only relevant if "grid" is chosen. 
  # n_gamma: 100 # 10  # Number of gamma grid points. Only relevant if "grid" is chosen. 
  generative_rules_to_test:  # wiring rules!! 
    - matching_index
    # - degree_product # clustering_coefficient does not work yet... 
    # - communicability 
  num_simulations: 10 # 00
  evaluation_metrics:
    - degree_ks
    - clustering_ks
    - edge_length_ks
    - betweenness_ks
  weight_criterion: distance_weighted_communicability
  alpha: 0.01

  distance_relationship_type: ["powerlaw"]
  preferential_relationship_type: ["powerlaw"]
  heterochronicity_relationship_type: ["powerlaw"]


dyn_gnm: # optional, only relevant for DynGNM
  dynamic_fitness_metric: "mc_mean" # Metric to optimize during dynamic generation.  "mc_mean", "branching_ratio", "info_balance", ...


esn: # (optional section)
  spectral_radius: 0.9 # 1.0] # [0.5, 1.0, 1.5, 2.0]  # List for grid search. Everything above around 1 is prob stable 
  input_scaling: 1.0 # 1.5 1.02] # [1e-5] #[0.5] # 1.0] # , 1.5]
  regression_method: "pinv"
  leak_rate: 1.0 # only relies on input data, not older data
  bias: 0.0 # 1.0 no constant bias added. 
  n_transient: 100 
  n_lags: 50
  train_len: 5000 # [500, 1000, 2000, 3000, 4000]
  test_len: 1000
  # regularization_methods: [pinv] # pinv] # pinv] #ridge] #pinv] #, ridge] #maybe ridge does not work? 
  n_runs: 50
  random_state: 42 #### IS THIS SENSIBLE??? TODO 



compute:
  device: "cpu"
  n_workers: 8 # 1 for debugging!!  # -1 for maximum parallelization # 12 # 14 cores - 10 normal, 4 efficiency. TODO: Is not satisfactory implemented, I guess... 
  timing_flag: true
  random_seed: 42


output:
  # root_dir: /Users/adrian/Documents/01_projects/14_4D_lab/14_4D_lab_code  # Override root directory
  # base_dir: ./output  # Possibility to override base output directory
  # experiment_name: my_experiment # TODO: TAKE THIS FROM ABOVE! 
  # save_intermediate: true # TODO: REMOVE THIS AGAIN! 
  figure_format: pdf # png
  verbosity: INFO
